#!/usr/bin/env python3
"""Install the systemd user units from config.toml.

Writes ~/.config/systemd/user/dawnchorus.{service,timer}, reloads systemd
and restarts the timer. Both files are generated; to change the time, edit
[schedule] in config.toml and run this again.

    python3 deploy/apply-schedule.py [--print]
"""

import argparse
import re
import subprocess
import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
UNIT_DIR = Path.home() / ".config" / "systemd" / "user"

TIMER = """\
# Generated by deploy/apply-schedule.py from config.toml. Don't edit.
[Unit]
Description=The Dawn Chorus, daily at {run_time} {timezone}

[Timer]
OnCalendar=*-*-* {run_time}:00 {timezone}
Persistent=true

[Install]
WantedBy=timers.target
"""


def units(cfg):
    sched = cfg["schedule"]
    if not re.fullmatch(r"([01]\d|2[0-3]):[0-5]\d", sched["run_time"]):
        raise SystemExit(f"run_time must be HH:MM, got {sched['run_time']!r}")
    service = (ROOT / "deploy" / "dawnchorus.service").read_text().replace("{root}", str(ROOT))
    return service, TIMER.format(**sched)


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--print", action="store_true", help="show the units, change nothing")
    args = ap.parse_args(argv)
    with open(ROOT / "config.toml", "rb") as f:
        service, timer = units(tomllib.load(f))
    if args.print:
        print(service, timer, sep="\n")
        return 0
    UNIT_DIR.mkdir(parents=True, exist_ok=True)
    (Path.home() / "backups").mkdir(exist_ok=True)
    (UNIT_DIR / "dawnchorus.service").write_text(service)
    (UNIT_DIR / "dawnchorus.timer").write_text(timer)
    for cmd in (["daemon-reload"], ["enable", "dawnchorus.timer"], ["restart", "dawnchorus.timer"]):
        subprocess.run(["systemctl", "--user", *cmd], check=True)
    subprocess.run(["systemctl", "--user", "list-timers", "dawnchorus.timer", "--no-pager"])
    return 0


if __name__ == "__main__":
    sys.exit(main())
